#=================================================
# Description: Build OpenWrt using GitHub Actions   
# Lisence: MIT
# Author:  2AYN
#=================================================
#  ____     _ __   ___   _ 
# |___ \   / \\ \ / / \ | |
#   __) | / _ \\ V /|  \| |
#  / __/ / ___ \| | | |\  |
# |_____/_/   \_\_| |_| \_|
         
  
name: Build x86_64 OpenWrt

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'


#在每月的1日的凌晨2点运行
  schedule:
     - cron: 0 2 1 * *


env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: master
  FEEDS_CONF: feeds.conf.default
  CONFIG_FILE: x86_64.config
  DIY_P1_SH: diy-part1.sh
  DIY_P2_SH: diy-part2.sh
  UPLOAD_BIN_DIR: false
  UPLOAD_FIRMWARE: true
  UPLOAD_RELEASE: true
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Check server performance
      run: |
        echo "test"
        [ -e CONFIG_FILE ] && echo $?
        [ -e CONFIG_FILE ]
        echo $?
        pwd
        ls
